-- SEED UNIVERSITIES DATA
-- Use ON CONFLICT to avoid duplicates

INSERT INTO universities (name) VALUES
('Abubakar Tafawa Balewa University, Bauchi'),
('Ahmadu Bello University, Zaria'),
('Bayero University, Kano'),
('Federal University of Agriculture, Abeokuta'),
('Federal University of Petroleum Resources, Effurun'),
('Federal University of Technology, Akure'),
('Federal University of Technology, Minna'),
('Federal University of Technology, Owerri'),
('Federal University, Birnin-Kebbi'),
('Federal University, Dutse'),
('Federal University, Dutsin-Ma'),
('Federal University, Gashua'),
('Federal University, Gusau'),
('Federal University, Kashere'),
('Federal University, Lafia'),
('Federal University, Lokoja'),
('Federal University, Otuoke'),
('Federal University, Oye-Ekiti'),
('Federal University, Wukari'),
('Federal University, Ndifu-Alike'),
('Federal University of Health Sciences, Azare'),
('Federal University of Health Sciences, Ila-Orangun'),
('Michael Okpara University of Agriculture, Umudike'),
('Modibbo Adama University, Yola'),
('National Open University of Nigeria'),
('Nigerian Defence Academy, Kaduna'),
('Nnamdi Azikiwe University, Awka'),
('Obafemi Awolowo University, Ile-Ife'),
('University of Abuja'),
('University of Benin'),
('University of Calabar'),
('University of Ibadan'),
('University of Ilorin'),
('University of Jos'),
('University of Lagos'),
('University of Maiduguri'),
('University of Nigeria, Nsukka'),
('University of Port Harcourt'),
('University of Uyo'),
('Usmanu Danfodiyo University, Sokoto'),
('Abia State University, Uturu'),
('Adamawa State University, Mubi'),
('Adekunle Ajasin University, Akungba-Akoko'),
('Akwa Ibom State University'),
('Ambrose Alli University, Ekpoma'),
('Bauchi State University, Gadau'),
('Benue State University, Makurdi'),
('Borno State University'),
('Chukwuemeka Odumegwu Ojukwu University'),
('Cross River University of Technology'),
('Delta State University, Abraka'),
('Ebonyi State University'),
('Edo State University, Uzairue'),
('Ekiti State University'),
('Enugu State University of Science and Technology'),
('Gombe State University'),
('Ibrahim Badamasi Babangida University, Lapai'),
('Ignatius Ajuru University of Education'),
('Imo State University'),
('Kaduna State University'),
('Kano State University of Science and Technology'),
('Kebbi State University of Science and Technology'),
('Kogi State University'),
('Kwara State University'),
('Lagos State University'),
('Nasarawa State University'),
('Niger State University of Education'),
('Olabisi Onabanjo University'),
('Ondo State University of Science and Technology'),
('Osun State University'),
('Plateau State University'),
('Rivers State University'),
('Sokoto State University'),
('Taraba State University'),
('Umaru Musa Yar’adua University'),
('Yobe State University'),
('Zamfara State University'),
('Achievers University, Owo'),
('Adeleke University, Ede'),
('Afe Babalola University, Ado-Ekiti'),
('African University of Science and Technology, Abuja'),
('Ahman Pategi University'),
('Ajayi Crowther University'),
('Al-Hikmah University'),
('Al-Qalam University'),
('American University of Nigeria'),
('Augustine University'),
('Babcock University'),
('Bells University of Technology'),
('Benson Idahosa University'),
('Bingham University'),
('Bowen University'),
('Caleb University'),
('Caritas University'),
('Chrisland University'),
('Clifford University'),
('Coal City University'),
('Covenant University'),
('Crawford University'),
('Dominican University'),
('Eastern Palm University'),
('Edwin Clark University'),
('Elizade University'),
('Evangel University'),
('Fountain University'),
('Godfrey Okoye University'),
('Gregory University'),
('Hallmark University'),
('Hezekiah University'),
('Igbinedion University'),
('Joseph Ayo Babalola University'),
('Kings University'),
('Kola Daisi University'),
('Landmark University'),
('Lead City University'),
('Madonna University'),
('McPherson University'),
('Mountain Top University'),
('Nile University of Nigeria'),
('Novena University'),
('Obong University'),
('Oduduwa University'),
('Pan-Atlantic University'),
('Paul University'),
('Redeemer’s University'),
('Renaissance University'),
('Rhema University'),
('Salem University'),
('Skyline University'),
('Summit University'),
('Tansian University'),
('Trinity University'),
('University of Mkar'),
('Veritas University'),
('Wellspring University')
ON CONFLICT (name) DO NOTHING;

-- SEED DEPARTMENTS (COMMON ONES)
-- Note: This is harder because it depends on university_id.
-- Let's just seed some common ones for ALL federal universities.

INSERT INTO departments (name, university_id)
SELECT d.name, u.id
FROM (VALUES 
  ('Computer Science'),
  ('Mechanical Engineering'),
  ('Electrical Engineering'),
  ('Civil Engineering'),
  ('Medicine and Surgery'),
  ('Pharmacy'),
  ('Law'),
  ('Accounting'),
  ('Business Administration'),
  ('Economics'),
  ('Political Science'),
  ('Mass Communication'),
  ('English Language'),
  ('Biochemistry'),
  ('Microbiology')
) AS d(name)
CROSS JOIN universities u
ON CONFLICT (name, university_id) DO NOTHING;
